# title shouldn't appear in toc
* Santander Customer Transaction Predictions (Kaggle) :noexport:

A brief exploration of the [[https://www.kaggle.com/c/santander-customer-transaction-prediction/overview][Kaggle: Santander Customer Transaction Predictions]] competition.

# insert the toc here
* Contents :TOC:
- [[#competition-description][Competition Description]]
- [[#the-data][The Data]]
- [[#brief-summary-of-my-exploration][Brief Summary of My Exploration]]

* Competition Description

We are told:

"In this challenge, we invite Kagglers to help us identify which customers will make a specific transaction in the future, irrespective of the amount of money transacted. The data provided for this competition has the same structure as the real data we have available to solve this problem."

* The Data

- 200 anonymous numeric features
- Binary target
- Model to be evaluated on auc 
- No missing values
- Many repeated values

The repeated values hint that perhaps these features have some categorical nature. More on this in the next section.

* Brief Summary of My Exploration

I was intrigued by this (already closed) competition as I was looking for some practice on a project with short training times and low preprocessing barriers. I also found the 200 anonymous numeric feature data to be quite unique and thus an intriguing puzzle.

With little hyperparameter tuning and no preprocessing, [[https://lightgbm.readthedocs.io][LightGBM]] and simple neural network models with a few hidden layers can score 0.90 auc or slightly lower. 

The [[https://www.kaggle.com/c/santander-customer-transaction-prediction/leaderboard][competition (private) leaderboard]] lists 0.92573 as 1st place. Experimenting with different architectures and hyperparameters suggested lead to little progress, so the conclusion was that I needed to do some feature engineering, 


